// import localFont from "next/font/local";
import "./globals.css";
import {Poppins} from 'next/font/google';


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const poppins_font = Poppins({
  subsets:['latin'],
  weight: ['300','400','500','600','700','800','900'],
  variable: '--font-poppins'

});


export const metadata = {
  title: "Numerical",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins_font.variable}/*`${geistSans.variable} ${geistMono.variable} antialiased`*/
      >
        {children}
      </body>
    </html>
  );
}
